### ISSUE TITLE
Game is crashing when sleeping after proxying item - XmlSerializer

### ISSUE THREAD

**Issue by ThatNorthernMonkey** [demmonic/Storm#2]
Initial Issue: stephen dini

Items that are created can not be serialized.
The problem is if you save the game with the new items you created while they are in the chest or in the inventory the game will crash. If you eat them or use or sell them it works.
This might be because some of the variables of the newly created item are throwing an error. https://goo.gl/CYbA6k

/////////////////////////////
http://pastebin.com/ZFJ3TNWQ

It seems the XmlSerializer is expecting a typeof(StardewValley.Object.Chest) (for example) and it is actually receiving the Castle.Proxies.ChestProxy (or the proxy of any other object that has been spawned).

**Comment by sorlok** [comment]
Hi @ThatNorthernMonkey , 

I ran into this issue when making my mod. In short, doing something like this:
```var newObj =  @event.Proxy<ObjectAccessor, ObjectItem>(new ObjectDelegate(Vector2.Zero, 792, "Vodka", false, true, false, false));```

...won't work. You need to do something like this:
```(ObjectAccessor)Activator.CreateInstance(/*StardewValley.Object, or whatever*/, new object[] { Vector2.Zero, 792, "Vodka", false, true, false, false });```

Presumably the Object Proxy can be modified to fix this, but for now creating the object directly is a reasonable workaround.

Sample code from my mod:
https://github.com/sorlok/StardewMeadMod/blob/master/MeadMod/MeadMod.cs#L281
